apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hocs-ui
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: hocs-ui
  targetCPUUtilizationPercentage: 80
