---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/secure-backends: "true"
    ingress.kubernetes.io/proxy-body-size: "20m'
  name: hocs-ui
spec:
  rules:
  - host: {{.DNS_PREFIX}}hocs.homeoffice.gov.uk
    http:
      paths:
      - backend:
          serviceName: hocs-ui
          servicePort: 443
        path: /
  tls:
  - hosts:
    - {{.DNS_PREFIX}}hocs.homeoffice.gov.uk
    secretName: letsencrypt-hocs-ui
