---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/secure-backends: "true"
    ingress.kubernetes.io/backend-protocol: "HTTPS"
    ingress.kubernetes.io/proxy-body-size: "20m"
    ingress.kubernetes.io/whitelist-source-range: {{.IP_WHITELIST}}
    kubernetes.io/ingress.class: nginx-external
    stable.k8s.psg.io/kcm.provider: http
  labels:
    stable.k8s.psg.io/kcm.class: default
  name: hocs-ui
spec:

  rules:
  - host: {{.DOMAIN_NAME}}
    http:
      paths:
      - backend:
          serviceName: hocs-ui
          servicePort: 443
        path: /
  - host: www.{{.DOMAIN_NAME}}
    http:
      paths:
      - backend:
          serviceName: hocs-ui
          servicePort: 443
        path: /
  - host: {{.LEGACY_DOMAIN_NAME}}
    http:
      paths:
      - backend:
          serviceName: hocs-ui
          servicePort: 443
        path: /
  - host: www.{{.LEGACY_DOMAIN_NAME}}
    http:
      paths:
      - backend:
          serviceName: hocs-ui
          servicePort: 443
        path: /
  tls:
  - hosts:
    - {{.DOMAIN_NAME}}
    - www.{{.DOMAIN_NAME}}
    - {{.LEGACY_DOMAIN_NAME}}
    - www.{{.LEGACY_DOMAIN_NAME}}
    secretName: letsencrypt-hocs-ui
